services:
  - type: web
    name: crm-advogado
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /icon-*.png
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /manifest.webmanifest
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
