/**
 * Catálogo de emojis do compositor do WhatsApp — dados + busca.
 *
 * Escrito à mão, e não puxado de uma biblioteca, por dois motivos práticos: o
 * pacote completo do Unicode passa de 1 MB só de metadados (entraria no bundle
 * do CRM inteiro para servir uma barra de mensagem), e as palavras-chave dele
 * vêm em inglês — quem atende digita "coracao", "obrigado", "risada".
 *
 * Cada item tem o caractere (`e`) e as palavras pelas quais ele é encontrado
 * (`k`), em português e sem acento: a busca também tira o acento do que foi
 * digitado, então "coração" e "coracao" acham a mesma coisa.
 *
 * Sem imports de propósito: módulo puro, para o ts-node do `npm test` carregá-lo
 * sem arrastar a cadeia do React (ver `testes-ts-node-imports`).
 */

export interface EmojiItem {
  /** O caractere em si. */
  e: string;
  /** Palavras-chave, separadas por espaço, minúsculas e sem acento. */
  k: string;
}

export interface EmojiGrupo {
  id: string;
  /** Rótulo da aba, em pt-BR. */
  nome: string;
  /** Emoji que representa o grupo na barra de abas. */
  icone: string;
  emojis: EmojiItem[];
}

/** As seis reações rápidas, na mesma ordem do aplicativo. */
export const REACOES_RAPIDAS = ['👍', '❤️', '😂', '😮', '😢', '🙏'] as const;

export const GRUPOS_DE_EMOJI: EmojiGrupo[] = [
  {
    id: 'rostos',
    nome: 'Rostos e emoções',
    icone: '😀',
    emojis: [
      { e: '😀', k: 'sorriso feliz alegre rosto' },
      { e: '😃', k: 'sorriso feliz alegre animado' },
      { e: '😄', k: 'sorriso feliz alegre riso' },
      { e: '😁', k: 'sorriso dentes feliz' },
      { e: '😆', k: 'risada gargalhada feliz' },
      { e: '😅', k: 'risada alivio suor nervoso' },
      { e: '🤣', k: 'risada rolando chorando de rir engracado' },
      { e: '😂', k: 'risada chorando de rir engracado lagrima' },
      { e: '🙂', k: 'sorriso leve simpatico' },
      { e: '🙃', k: 'de cabeca para baixo ironia sarcasmo' },
      { e: '😉', k: 'piscada flerte brincadeira' },
      { e: '😊', k: 'sorriso timido feliz gentil' },
      { e: '😇', k: 'anjo santo inocente aureola' },
      { e: '🥰', k: 'apaixonado amor coracoes carinho' },
      { e: '😍', k: 'apaixonado amor olhos de coracao' },
      { e: '🤩', k: 'estrela deslumbrado uau incrivel' },
      { e: '😘', k: 'beijo amor carinho' },
      { e: '😗', k: 'beijo assobio' },
      { e: '😚', k: 'beijo carinho' },
      { e: '😙', k: 'beijo sorriso' },
      { e: '😋', k: 'delicioso gostoso lingua saboroso' },
      { e: '😛', k: 'lingua brincadeira' },
      { e: '😜', k: 'lingua piscada brincadeira' },
      { e: '🤪', k: 'maluco doido brincadeira' },
      { e: '😝', k: 'lingua brincadeira careta' },
      { e: '🤑', k: 'dinheiro rico cifrao' },
      { e: '🤗', k: 'abraco carinho acolhida' },
      { e: '🤭', k: 'ops vergonha risinho mao na boca' },
      { e: '🤫', k: 'silencio segredo shh' },
      { e: '🤔', k: 'pensando duvida hmm reflexao' },
      { e: '🤐', k: 'boca fechada segredo calado' },
      { e: '🤨', k: 'desconfiado sobrancelha duvida' },
      { e: '😐', k: 'neutro sem expressao' },
      { e: '😑', k: 'inexpressivo entediado' },
      { e: '😶', k: 'sem boca calado mudo' },
      { e: '😏', k: 'sorriso maroto malicia' },
      { e: '😒', k: 'insatisfeito contrariado chateado' },
      { e: '🙄', k: 'revirando os olhos ironia' },
      { e: '😬', k: 'careta constrangido nervoso' },
      { e: '🤥', k: 'mentira nariz pinoquio' },
      { e: '😌', k: 'aliviado tranquilo calmo' },
      { e: '😔', k: 'triste pensativo cabisbaixo' },
      { e: '😪', k: 'sono cansado sonolento' },
      { e: '🤤', k: 'babando desejo fome' },
      { e: '😴', k: 'dormindo sono zzz' },
      { e: '😷', k: 'mascara doente gripe' },
      { e: '🤒', k: 'doente febre termometro' },
      { e: '🤕', k: 'machucado ferido curativo' },
      { e: '🤢', k: 'enjoado nojo mal estar' },
      { e: '🤮', k: 'vomito enjoo nojo' },
      { e: '🤧', k: 'espirro resfriado gripe' },
      { e: '🥵', k: 'calor quente derretendo' },
      { e: '🥶', k: 'frio congelando gelado' },
      { e: '😵', k: 'tonto atordoado confuso' },
      { e: '🤯', k: 'explodindo mente chocado inacreditavel' },
      { e: '🤠', k: 'cauboi chapeu' },
      { e: '🥳', k: 'festa comemoracao aniversario' },
      { e: '😎', k: 'oculos de sol estiloso tranquilo' },
      { e: '🤓', k: 'nerd estudioso oculos' },
      { e: '🧐', k: 'monoculo analisando curioso' },
      { e: '😕', k: 'confuso incerto' },
      { e: '😟', k: 'preocupado aflito' },
      { e: '🙁', k: 'triste chateado' },
      { e: '😮', k: 'surpreso boca aberta uau' },
      { e: '😯', k: 'surpreso espantado' },
      { e: '😲', k: 'chocado espantado surpresa' },
      { e: '😳', k: 'envergonhado corado surpreso' },
      { e: '🥺', k: 'suplicante pedindo carinha de pena' },
      { e: '😦', k: 'assustado preocupado' },
      { e: '😨', k: 'medo assustado' },
      { e: '😰', k: 'ansioso nervoso suor' },
      { e: '😥', k: 'triste aliviado decepcionado' },
      { e: '😢', k: 'chorando triste lagrima' },
      { e: '😭', k: 'chorando muito triste desesperado' },
      { e: '😱', k: 'grito panico medo susto' },
      { e: '😖', k: 'angustiado incomodado' },
      { e: '😣', k: 'perseverando esforco dor' },
      { e: '😞', k: 'decepcionado desanimado' },
      { e: '😓', k: 'suor derrotado cansado' },
      { e: '😩', k: 'exausto cansado desesperado' },
      { e: '😫', k: 'cansado exausto' },
      { e: '🥱', k: 'bocejo sono tedio' },
      { e: '😤', k: 'bufando irritado determinado' },
      { e: '😡', k: 'bravo raiva furioso' },
      { e: '😠', k: 'bravo irritado raiva' },
      { e: '🤬', k: 'palavrao xingando furioso' },
      { e: '😈', k: 'diabinho travesso malvado' },
      { e: '💀', k: 'caveira morte morri de rir' },
      { e: '🤡', k: 'palhaco piada' },
      { e: '👻', k: 'fantasma assombracao halloween' },
      { e: '👽', k: 'alienigena et' },
      { e: '🤖', k: 'robo automatico ia' },
      { e: '💩', k: 'coco merda ruim' },
    ],
  },
  {
    id: 'gestos',
    nome: 'Gestos e pessoas',
    icone: '👍',
    emojis: [
      { e: '👍', k: 'joinha positivo ok curtir concordo like' },
      { e: '👎', k: 'negativo nao gostei descurtir' },
      { e: '👌', k: 'ok certo perfeito' },
      { e: '🤌', k: 'italiano gesto dedos' },
      { e: '✌️', k: 'paz e amor vitoria dois' },
      { e: '🤞', k: 'dedos cruzados torcendo sorte' },
      { e: '🤟', k: 'te amo rock mao' },
      { e: '🤘', k: 'rock chifrinho' },
      { e: '🤙', k: 'me liga shaka telefone' },
      { e: '👈', k: 'aponta esquerda' },
      { e: '👉', k: 'aponta direita' },
      { e: '👆', k: 'aponta cima' },
      { e: '👇', k: 'aponta baixo abaixo' },
      { e: '☝️', k: 'atencao um dedo acima' },
      { e: '✋', k: 'mao parada stop alto' },
      { e: '🤚', k: 'mao levantada' },
      { e: '🖐️', k: 'mao aberta dedos' },
      { e: '🖖', k: 'saudacao vulcano' },
      { e: '👋', k: 'tchau ola oi aceno bom dia' },
      { e: '🤝', k: 'aperto de mao acordo negocio parceria' },
      { e: '🙏', k: 'obrigado por favor oracao reza agradecido' },
      { e: '✍️', k: 'escrevendo assinatura anotando' },
      { e: '💪', k: 'forca musculo firme' },
      { e: '👏', k: 'palmas aplauso parabens' },
      { e: '🙌', k: 'maos para cima comemorando aleluia' },
      { e: '👐', k: 'maos abertas abraco' },
      { e: '🤲', k: 'maos juntas pedido' },
      { e: '🫶', k: 'coracao com as maos amor' },
      { e: '✊', k: 'punho forca resistencia' },
      { e: '👊', k: 'soco punho toca aqui' },
      { e: '🤛', k: 'punho esquerda' },
      { e: '🤜', k: 'punho direita' },
      { e: '🫰', k: 'dedos dinheiro estalo' },
      { e: '👀', k: 'olhos olhando vendo atencao' },
      { e: '🧠', k: 'cerebro ideia inteligencia' },
      { e: '👶', k: 'bebe crianca recem nascido' },
      { e: '🧑', k: 'pessoa adulto' },
      { e: '👨', k: 'homem' },
      { e: '👩', k: 'mulher' },
      { e: '🧓', k: 'idoso velho aposentado' },
      { e: '👴', k: 'senhor idoso aposentado' },
      { e: '👵', k: 'senhora idosa aposentada' },
      { e: '👮', k: 'policial guarda' },
      { e: '🕵️', k: 'detetive investigacao' },
      { e: '👨‍⚖️', k: 'juiz justica tribunal' },
      { e: '👩‍⚖️', k: 'juiza justica tribunal' },
      { e: '👨‍💼', k: 'advogado executivo escritorio terno' },
      { e: '👩‍💼', k: 'advogada executiva escritorio' },
      { e: '👨‍⚕️', k: 'medico saude perito' },
      { e: '👩‍⚕️', k: 'medica saude perita' },
      { e: '🧑‍💻', k: 'computador trabalho digitando' },
      { e: '👨‍👩‍👧', k: 'familia pais filha' },
      { e: '🤰', k: 'gravida gestante maternidade' },
      { e: '🧑‍🦽', k: 'cadeira de rodas deficiencia' },
      { e: '🧑‍🦯', k: 'bengala cego deficiencia visual' },
      { e: '🤦', k: 'facepalm decepcao nao acredito' },
      { e: '🤷', k: 'nao sei ombros sei la' },
      { e: '💃', k: 'dancando festa' },
      { e: '🕺', k: 'dancando festa homem' },
      { e: '🚶', k: 'andando caminhando' },
      { e: '🏃', k: 'correndo pressa' },
    ],
  },
  {
    id: 'coracoes',
    nome: 'Coração e símbolos',
    icone: '❤️',
    emojis: [
      { e: '❤️', k: 'coracao amor vermelho' },
      { e: '🧡', k: 'coracao laranja amor' },
      { e: '💛', k: 'coracao amarelo amor amizade' },
      { e: '💚', k: 'coracao verde amor' },
      { e: '💙', k: 'coracao azul amor' },
      { e: '💜', k: 'coracao roxo amor' },
      { e: '🖤', k: 'coracao preto luto' },
      { e: '🤍', k: 'coracao branco paz' },
      { e: '🤎', k: 'coracao marrom' },
      { e: '💔', k: 'coracao partido tristeza termino' },
      { e: '❣️', k: 'coracao exclamacao amor' },
      { e: '💕', k: 'dois coracoes amor' },
      { e: '💞', k: 'coracoes girando amor' },
      { e: '💓', k: 'coracao batendo amor' },
      { e: '💗', k: 'coracao crescendo amor' },
      { e: '💖', k: 'coracao brilhando amor' },
      { e: '💘', k: 'coracao flechado cupido paixao' },
      { e: '💝', k: 'coracao presente amor' },
      { e: '💯', k: 'cem nota maxima perfeito exato' },
      { e: '✅', k: 'certo confirmado ok feito verde' },
      { e: '☑️', k: 'marcado confirmado' },
      { e: '✔️', k: 'certo confirmado feito' },
      { e: '❌', k: 'errado cancelado nao x' },
      { e: '⛔', k: 'proibido parar bloqueado' },
      { e: '🚫', k: 'proibido bloqueado nao pode' },
      { e: '⚠️', k: 'atencao alerta cuidado aviso' },
      { e: '❗', k: 'exclamacao importante atencao' },
      { e: '❓', k: 'interrogacao duvida pergunta' },
      { e: '💬', k: 'balao mensagem conversa' },
      { e: '💭', k: 'pensamento balao' },
      { e: '🔔', k: 'sino aviso notificacao lembrete' },
      { e: '🔕', k: 'silenciado sino cortado' },
      { e: '⭐', k: 'estrela favorito destaque' },
      { e: '🌟', k: 'estrela brilhante destaque' },
      { e: '✨', k: 'brilho novidade magia' },
      { e: '🔥', k: 'fogo quente sucesso top' },
      { e: '💥', k: 'explosao impacto' },
      { e: '⚡', k: 'raio energia rapido urgente' },
      { e: '🎉', k: 'festa comemoracao parabens' },
      { e: '🎊', k: 'confete festa comemoracao' },
      { e: '🎁', k: 'presente aniversario' },
      { e: '🏆', k: 'trofeu vitoria ganhou' },
      { e: '🥇', k: 'medalha ouro primeiro' },
      { e: '♻️', k: 'reciclagem sustentavel' },
      { e: '🆗', k: 'ok certo' },
      { e: '🆘', k: 'socorro emergencia ajuda' },
      { e: '🔴', k: 'circulo vermelho parado' },
      { e: '🟡', k: 'circulo amarelo atencao' },
      { e: '🟢', k: 'circulo verde ok liberado' },
      { e: '🔵', k: 'circulo azul' },
    ],
  },
  {
    id: 'trabalho',
    nome: 'Trabalho e documentos',
    icone: '📄',
    emojis: [
      { e: '📄', k: 'documento papel folha peticao' },
      { e: '📃', k: 'documento papel enrolado' },
      { e: '📑', k: 'marcadores documentos separadores' },
      { e: '📋', k: 'prancheta lista checklist' },
      { e: '📁', k: 'pasta arquivo processo' },
      { e: '📂', k: 'pasta aberta arquivo' },
      { e: '🗂️', k: 'arquivos organizacao pastas' },
      { e: '🗃️', k: 'arquivo caixa fichario' },
      { e: '📊', k: 'grafico barras relatorio' },
      { e: '📈', k: 'grafico subindo crescimento aumento' },
      { e: '📉', k: 'grafico caindo queda reducao' },
      { e: '📌', k: 'alfinete fixar importante' },
      { e: '📎', k: 'clipe anexo arquivo' },
      { e: '✂️', k: 'tesoura cortar' },
      { e: '📝', k: 'anotacao escrever nota rascunho' },
      { e: '🖊️', k: 'caneta assinar escrever' },
      { e: '✏️', k: 'lapis escrever editar' },
      { e: '📚', k: 'livros estudo doutrina' },
      { e: '📖', k: 'livro aberto leitura lei' },
      { e: '⚖️', k: 'balanca justica direito advogado processo' },
      { e: '🏛️', k: 'tribunal forum predio justica inss' },
      { e: '👨‍⚖️', k: 'juiz audiencia' },
      { e: '🔍', k: 'lupa buscar pesquisar consultar' },
      { e: '🔎', k: 'lupa buscar pesquisa' },
      { e: '🔒', k: 'cadeado fechado seguro sigilo' },
      { e: '🔓', k: 'cadeado aberto liberado' },
      { e: '🔑', k: 'chave acesso senha' },
      { e: '📅', k: 'calendario data agenda prazo' },
      { e: '📆', k: 'calendario data agenda' },
      { e: '🗓️', k: 'calendario agenda mes' },
      { e: '⏰', k: 'despertador alarme lembrete hora' },
      { e: '⏳', k: 'ampulheta prazo esperando tempo' },
      { e: '⌛', k: 'ampulheta tempo acabando prazo' },
      { e: '🕐', k: 'relogio hora horario' },
      { e: '💼', k: 'maleta trabalho escritorio' },
      { e: '💻', k: 'notebook computador trabalho' },
      { e: '🖥️', k: 'computador monitor' },
      { e: '📱', k: 'celular telefone whatsapp' },
      { e: '☎️', k: 'telefone ligacao' },
      { e: '📞', k: 'telefone ligacao chamada' },
      { e: '📲', k: 'celular chamada me liga' },
      { e: '📧', k: 'email correio mensagem' },
      { e: '✉️', k: 'carta email envelope' },
      { e: '📨', k: 'mensagem recebida email' },
      { e: '📤', k: 'enviado caixa de saida' },
      { e: '📥', k: 'recebido caixa de entrada' },
      { e: '🖨️', k: 'impressora imprimir' },
      { e: '🗑️', k: 'lixeira apagar excluir' },
      { e: '💰', k: 'dinheiro pagamento valor honorarios' },
      { e: '💵', k: 'dinheiro nota real pagamento' },
      { e: '💳', k: 'cartao pagamento credito' },
      { e: '🧾', k: 'recibo comprovante nota fiscal' },
      { e: '🏦', k: 'banco agencia' },
      { e: '🏥', k: 'hospital pericia medica saude' },
      { e: '🚑', k: 'ambulancia emergencia acidente' },
      { e: '🏠', k: 'casa residencia endereco' },
      { e: '🚗', k: 'carro veiculo acidente' },
      { e: '🛠️', k: 'ferramentas manutencao trabalho' },
      { e: '📍', k: 'local endereco marcador mapa' },
      { e: '🗺️', k: 'mapa localizacao' },
      { e: '🔗', k: 'link ligacao vinculo' },
    ],
  },
  {
    id: 'natureza',
    nome: 'Natureza e comida',
    icone: '🌻',
    emojis: [
      { e: '🌞', k: 'sol bom dia dia' },
      { e: '🌙', k: 'lua noite boa noite' },
      { e: '⛅', k: 'nublado tempo nuvem' },
      { e: '🌧️', k: 'chuva chovendo tempo' },
      { e: '🌈', k: 'arco iris esperanca' },
      { e: '❄️', k: 'neve frio floco' },
      { e: '🌊', k: 'onda mar agua' },
      { e: '🌱', k: 'muda planta crescimento' },
      { e: '🌳', k: 'arvore natureza' },
      { e: '🌵', k: 'cacto deserto' },
      { e: '🌷', k: 'tulipa flor' },
      { e: '🌸', k: 'flor cerejeira' },
      { e: '🌺', k: 'flor hibisco' },
      { e: '🌻', k: 'girassol flor sol' },
      { e: '🌹', k: 'rosa flor amor' },
      { e: '💐', k: 'buque flores parabens' },
      { e: '🍀', k: 'trevo sorte' },
      { e: '🐶', k: 'cachorro cao pet' },
      { e: '🐱', k: 'gato gata pet' },
      { e: '🐭', k: 'rato' },
      { e: '🐦', k: 'passaro ave' },
      { e: '🐴', k: 'cavalo' },
      { e: '🐄', k: 'vaca gado boi' },
      { e: '🐷', k: 'porco' },
      { e: '🐔', k: 'galinha frango' },
      { e: '🐝', k: 'abelha' },
      { e: '🦋', k: 'borboleta' },
      { e: '🐟', k: 'peixe' },
      { e: '☕', k: 'cafe cafezinho bebida' },
      { e: '🍵', k: 'cha bebida' },
      { e: '🍺', k: 'cerveja bebida' },
      { e: '🍷', k: 'vinho bebida taca' },
      { e: '🥤', k: 'refrigerante bebida copo' },
      { e: '💧', k: 'agua gota' },
      { e: '🍞', k: 'pao padaria' },
      { e: '🧀', k: 'queijo' },
      { e: '🍕', k: 'pizza comida' },
      { e: '🍔', k: 'hamburguer lanche' },
      { e: '🍟', k: 'batata frita lanche' },
      { e: '🌭', k: 'cachorro quente lanche' },
      { e: '🍿', k: 'pipoca cinema' },
      { e: '🍎', k: 'maca fruta' },
      { e: '🍌', k: 'banana fruta' },
      { e: '🍇', k: 'uva fruta' },
      { e: '🍓', k: 'morango fruta' },
      { e: '🍉', k: 'melancia fruta' },
      { e: '🥗', k: 'salada comida saudavel' },
      { e: '🍚', k: 'arroz comida' },
      { e: '🍛', k: 'comida prato almoco' },
      { e: '🎂', k: 'bolo aniversario parabens' },
      { e: '🍰', k: 'bolo fatia doce' },
      { e: '🍫', k: 'chocolate doce' },
      { e: '🍬', k: 'bala doce' },
      { e: '🥂', k: 'brinde comemoracao tacas' },
    ],
  },
  {
    id: 'atividades',
    nome: 'Atividades e viagem',
    icone: '⚽',
    emojis: [
      { e: '⚽', k: 'futebol bola jogo' },
      { e: '🏀', k: 'basquete bola' },
      { e: '🏐', k: 'volei bola' },
      { e: '🎾', k: 'tenis bola' },
      { e: '🏈', k: 'futebol americano' },
      { e: '🎱', k: 'sinuca bilhar' },
      { e: '🎯', k: 'alvo objetivo meta' },
      { e: '🎮', k: 'videogame jogo' },
      { e: '🎲', k: 'dado sorte jogo' },
      { e: '🧩', k: 'quebra cabeca peca' },
      { e: '🎨', k: 'arte pintura' },
      { e: '🎤', k: 'microfone cantar audio' },
      { e: '🎧', k: 'fone de ouvido audio musica' },
      { e: '🎵', k: 'musica nota' },
      { e: '🎬', k: 'cinema filme claquete' },
      { e: '📷', k: 'camera foto' },
      { e: '📹', k: 'video camera filmagem' },
      { e: '🎥', k: 'video filmadora' },
      { e: '📺', k: 'televisao tv' },
      { e: '📻', k: 'radio' },
      { e: '✈️', k: 'aviao viagem voo' },
      { e: '🚌', k: 'onibus transporte' },
      { e: '🚕', k: 'taxi carro' },
      { e: '🚓', k: 'policia viatura' },
      { e: '🚒', k: 'bombeiros caminhao' },
      { e: '🚚', k: 'caminhao entrega transporte' },
      { e: '🏍️', k: 'moto motocicleta' },
      { e: '🚲', k: 'bicicleta bike' },
      { e: '⛵', k: 'barco vela' },
      { e: '🚢', k: 'navio' },
      { e: '🚀', k: 'foguete lancamento rapido' },
      { e: '🏖️', k: 'praia ferias descanso' },
      { e: '⛰️', k: 'montanha' },
      { e: '🏙️', k: 'cidade predios' },
      { e: '🌍', k: 'mundo terra planeta' },
      { e: '🇧🇷', k: 'brasil bandeira brasileiro' },
    ],
  },
];

/** Todos os emojis, na ordem dos grupos — usado pela busca. */
export const TODOS_OS_EMOJIS: EmojiItem[] = GRUPOS_DE_EMOJI.flatMap(g => g.emojis);

/** Minúsculas e sem acento: é assim que a busca compara os dois lados. */
export function normalizarBusca(texto: string): string {
  return texto
    .toLocaleLowerCase('pt-BR')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

/**
 * Emojis que casam com o termo digitado.
 *
 * O casamento é por INÍCIO DE PALAVRA, não por trecho solto: "paz" encontrar
 * "capaz" faria a busca devolver justamente o que não se procurava. Com termo
 * vazio devolve nada — quem manda na tela nesse caso é o grupo selecionado.
 */
export function buscarEmojis(termo: string, limite = 60): EmojiItem[] {
  const alvo = normalizarBusca(termo);
  if (!alvo) return [];
  const achados: EmojiItem[] = [];
  for (const item of TODOS_OS_EMOJIS) {
    const casa = item.k.split(' ').some(palavra => palavra.startsWith(alvo));
    if (!casa) continue;
    achados.push(item);
    if (achados.length >= limite) break;
  }
  return achados;
}
